// Mocks generated by Mockito 5.4.6 from annotations
// in auror/test/helpers/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i13;

import 'package:auror/layers/data/api/api_client.dart' as _i12;
import 'package:auror/layers/data/client/auth_client.dart' as _i14;
import 'package:auror/layers/data/datasource/api_data_source.dart' as _i16;
import 'package:auror/layers/data/datasource/auth_data_source.dart' as _i15;
import 'package:auror/layers/data/models/profile_data.dart' as _i2;
import 'package:auror/layers/data/models/subscription_data.dart' as _i3;
import 'package:auror/layers/domain/models/category_domain.dart' as _i32;
import 'package:auror/layers/domain/models/guided_route_intro_domain.dart'
    as _i35;
import 'package:auror/layers/domain/models/idea_domain.dart' as _i8;
import 'package:auror/layers/domain/models/knowledge_card_domain.dart' as _i9;
import 'package:auror/layers/domain/models/membership_domain.dart' as _i10;
import 'package:auror/layers/domain/models/profile_domain.dart' as _i4;
import 'package:auror/layers/domain/models/revision_domain.dart' as _i11;
import 'package:auror/layers/domain/models/revision_section_domain.dart' as _i7;
import 'package:auror/layers/domain/models/subscription_domain.dart' as _i5;
import 'package:auror/layers/domain/models/user_domain.dart' as _i6;
import 'package:auror/layers/domain/repository/auth_repository.dart' as _i17;
import 'package:auror/layers/domain/repository/profile_repository.dart' as _i18;
import 'package:auror/layers/domain/repository/subscription_repository.dart'
    as _i19;
import 'package:auror/layers/domain/usecases/cancel_subscription.dart' as _i30;
import 'package:auror/layers/domain/usecases/get_card_revision.dart' as _i39;
import 'package:auror/layers/domain/usecases/get_categories.dart' as _i31;
import 'package:auror/layers/domain/usecases/get_current_subscription.dart'
    as _i27;
import 'package:auror/layers/domain/usecases/get_daily_idea.dart' as _i22;
import 'package:auror/layers/domain/usecases/get_guided_route_intros.dart'
    as _i34;
import 'package:auror/layers/domain/usecases/get_membership.dart' as _i36;
import 'package:auror/layers/domain/usecases/get_next_card.dart' as _i33;
import 'package:auror/layers/domain/usecases/get_profile.dart' as _i26;
import 'package:auror/layers/domain/usecases/get_revisions.dart' as _i21;
import 'package:auror/layers/domain/usecases/get_subscriptions.dart' as _i28;
import 'package:auror/layers/domain/usecases/get_user.dart' as _i20;
import 'package:auror/layers/domain/usecases/save_recall_card.dart' as _i37;
import 'package:auror/layers/domain/usecases/select_subscription.dart' as _i29;
import 'package:auror/layers/domain/usecases/send_answer.dart' as _i38;
import 'package:auror/layers/domain/usecases/sign_in.dart' as _i23;
import 'package:auror/layers/domain/usecases/sign_out.dart' as _i25;
import 'package:auror/layers/domain/usecases/sign_up.dart' as _i24;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i41;
import 'package:supabase_flutter/supabase_flutter.dart' as _i40;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeProfileData_0 extends _i1.SmartFake implements _i2.ProfileData {
  _FakeProfileData_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSubscriptionData_1 extends _i1.SmartFake
    implements _i3.SubscriptionData {
  _FakeSubscriptionData_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProfileDomain_2 extends _i1.SmartFake implements _i4.ProfileDomain {
  _FakeProfileDomain_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSubscriptionDomain_3 extends _i1.SmartFake
    implements _i5.SubscriptionDomain {
  _FakeSubscriptionDomain_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserDomain_4 extends _i1.SmartFake implements _i6.UserDomain {
  _FakeUserDomain_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRevisionSectionDomain_5 extends _i1.SmartFake
    implements _i7.RevisionSectionDomain {
  _FakeRevisionSectionDomain_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIdeaDomain_6 extends _i1.SmartFake implements _i8.IdeaDomain {
  _FakeIdeaDomain_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeKnowledgeCardDomain_7 extends _i1.SmartFake
    implements _i9.KnowledgeCardDomain {
  _FakeKnowledgeCardDomain_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMembershipDomain_8 extends _i1.SmartFake
    implements _i10.MembershipDomain {
  _FakeMembershipDomain_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRevisionDomain_9 extends _i1.SmartFake
    implements _i11.RevisionDomain {
  _FakeRevisionDomain_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockIApiClient extends _i1.Mock implements _i12.IApiClient {
  MockIApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<dynamic> get({
    required String? endpoint,
    Map<String, dynamic>? queryParameters = const {},
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(#get, [], {
              #endpoint: endpoint,
              #queryParameters: queryParameters,
              #headers: headers,
            }),
            returnValue: _i13.Future<dynamic>.value(),
          )
          as _i13.Future<dynamic>);

  @override
  _i13.Future<dynamic> post({
    required String? endpoint,
    Object? body,
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(#post, [], {
              #endpoint: endpoint,
              #body: body,
              #headers: headers,
            }),
            returnValue: _i13.Future<dynamic>.value(),
          )
          as _i13.Future<dynamic>);
}

/// A class which mocks [IAuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAuthService extends _i1.Mock implements _i14.IAuthService {
  MockIAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<void> signUp({
    required String? email,
    required String? password,
    required String? displayName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [], {
              #email: email,
              #password: password,
              #displayName: displayName,
            }),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> signIn({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);
}

/// A class which mocks [IAuthDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAuthDataSource extends _i1.Mock implements _i15.IAuthDataSource {
  MockIAuthDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<void> signUp({
    required String? email,
    required String? password,
    required String? displayName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [], {
              #email: email,
              #password: password,
              #displayName: displayName,
            }),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> signIn({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);
}

/// A class which mocks [IApiDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockIApiDataSource extends _i1.Mock implements _i16.IApiDataSource {
  MockIApiDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i2.ProfileData> fetchProfile({required String? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#fetchProfile, [], {#userId: userId}),
            returnValue: _i13.Future<_i2.ProfileData>.value(
              _FakeProfileData_0(
                this,
                Invocation.method(#fetchProfile, [], {#userId: userId}),
              ),
            ),
          )
          as _i13.Future<_i2.ProfileData>);

  @override
  _i13.Future<List<_i3.SubscriptionData>> fetchSubscriptions({
    String? resourceName = 'full_subscriptions',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchSubscriptions, [], {
              #resourceName: resourceName,
            }),
            returnValue: _i13.Future<List<_i3.SubscriptionData>>.value(
              <_i3.SubscriptionData>[],
            ),
          )
          as _i13.Future<List<_i3.SubscriptionData>>);

  @override
  _i13.Future<_i3.SubscriptionData> fetchCurrentSubscription({
    String? resourceName = 'full_subscriptions',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCurrentSubscription, [], {
              #resourceName: resourceName,
            }),
            returnValue: _i13.Future<_i3.SubscriptionData>.value(
              _FakeSubscriptionData_1(
                this,
                Invocation.method(#fetchCurrentSubscription, [], {
                  #resourceName: resourceName,
                }),
              ),
            ),
          )
          as _i13.Future<_i3.SubscriptionData>);

  @override
  _i13.Future<void> selectSubscription({
    required String? subscriptionId,
    String? rpcName = 'set_user_subscription',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#selectSubscription, [], {
              #subscriptionId: subscriptionId,
              #rpcName: rpcName,
            }),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> cancelSubscription({
    String? rpcName = 'cancel_user_subscription',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#cancelSubscription, [], {#rpcName: rpcName}),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);
}

/// A class which mocks [IAuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAuthRepository extends _i1.Mock implements _i17.IAuthRepository {
  MockIAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<void> signUp({
    required String? email,
    required String? password,
    required String? displayName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [], {
              #email: email,
              #password: password,
              #displayName: displayName,
            }),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> signIn({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);
}

/// A class which mocks [IProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIProfileRepository extends _i1.Mock
    implements _i18.IProfileRepository {
  MockIProfileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i4.ProfileDomain> getProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getProfile, []),
            returnValue: _i13.Future<_i4.ProfileDomain>.value(
              _FakeProfileDomain_2(this, Invocation.method(#getProfile, [])),
            ),
          )
          as _i13.Future<_i4.ProfileDomain>);
}

/// A class which mocks [ISubscriptionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockISubscriptionRepository extends _i1.Mock
    implements _i19.ISubscriptionRepository {
  MockISubscriptionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<List<_i5.SubscriptionDomain>> getSubscriptions() =>
      (super.noSuchMethod(
            Invocation.method(#getSubscriptions, []),
            returnValue: _i13.Future<List<_i5.SubscriptionDomain>>.value(
              <_i5.SubscriptionDomain>[],
            ),
          )
          as _i13.Future<List<_i5.SubscriptionDomain>>);

  @override
  _i13.Future<void> selectSubscription({required String? id}) =>
      (super.noSuchMethod(
            Invocation.method(#selectSubscription, [], {#id: id}),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> cancelSubscription() =>
      (super.noSuchMethod(
            Invocation.method(#cancelSubscription, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<_i5.SubscriptionDomain> getCurrentSubscription() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentSubscription, []),
            returnValue: _i13.Future<_i5.SubscriptionDomain>.value(
              _FakeSubscriptionDomain_3(
                this,
                Invocation.method(#getCurrentSubscription, []),
              ),
            ),
          )
          as _i13.Future<_i5.SubscriptionDomain>);
}

/// A class which mocks [IGetUser].
///
/// See the documentation for Mockito's code generation for more information.
class MockIGetUser extends _i1.Mock implements _i20.IGetUser {
  MockIGetUser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i6.UserDomain> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i13.Future<_i6.UserDomain>.value(
              _FakeUserDomain_4(this, Invocation.method(#call, [])),
            ),
          )
          as _i13.Future<_i6.UserDomain>);
}

/// A class which mocks [IGetRevisions].
///
/// See the documentation for Mockito's code generation for more information.
class MockIGetRevisions extends _i1.Mock implements _i21.IGetRevisions {
  MockIGetRevisions() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i7.RevisionSectionDomain> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i13.Future<_i7.RevisionSectionDomain>.value(
              _FakeRevisionSectionDomain_5(this, Invocation.method(#call, [])),
            ),
          )
          as _i13.Future<_i7.RevisionSectionDomain>);
}

/// A class which mocks [IGetDailyIdea].
///
/// See the documentation for Mockito's code generation for more information.
class MockIGetDailyIdea extends _i1.Mock implements _i22.IGetDailyIdea {
  MockIGetDailyIdea() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i8.IdeaDomain> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i13.Future<_i8.IdeaDomain>.value(
              _FakeIdeaDomain_6(this, Invocation.method(#call, [])),
            ),
          )
          as _i13.Future<_i8.IdeaDomain>);
}

/// A class which mocks [ISignIn].
///
/// See the documentation for Mockito's code generation for more information.
class MockISignIn extends _i1.Mock implements _i23.ISignIn {
  MockISignIn() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<void> call({required String? email, required String? password}) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#email: email, #password: password}),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);
}

/// A class which mocks [ISignUp].
///
/// See the documentation for Mockito's code generation for more information.
class MockISignUp extends _i1.Mock implements _i24.ISignUp {
  MockISignUp() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<void> call({
    required String? email,
    required String? password,
    required String? displayName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #email: email,
              #password: password,
              #displayName: displayName,
            }),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);
}

/// A class which mocks [ISignOut].
///
/// See the documentation for Mockito's code generation for more information.
class MockISignOut extends _i1.Mock implements _i25.ISignOut {
  MockISignOut() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<void> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);
}

/// A class which mocks [IGetProfile].
///
/// See the documentation for Mockito's code generation for more information.
class MockIGetProfile extends _i1.Mock implements _i26.IGetProfile {
  MockIGetProfile() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i4.ProfileDomain> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i13.Future<_i4.ProfileDomain>.value(
              _FakeProfileDomain_2(this, Invocation.method(#call, [])),
            ),
          )
          as _i13.Future<_i4.ProfileDomain>);
}

/// A class which mocks [IGetCurrentSubscription].
///
/// See the documentation for Mockito's code generation for more information.
class MockIGetCurrentSubscription extends _i1.Mock
    implements _i27.IGetCurrentSubscription {
  MockIGetCurrentSubscription() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i5.SubscriptionDomain> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i13.Future<_i5.SubscriptionDomain>.value(
              _FakeSubscriptionDomain_3(this, Invocation.method(#call, [])),
            ),
          )
          as _i13.Future<_i5.SubscriptionDomain>);
}

/// A class which mocks [IGetSubscriptions].
///
/// See the documentation for Mockito's code generation for more information.
class MockIGetSubscriptions extends _i1.Mock implements _i28.IGetSubscriptions {
  MockIGetSubscriptions() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<List<_i5.SubscriptionDomain>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i13.Future<List<_i5.SubscriptionDomain>>.value(
              <_i5.SubscriptionDomain>[],
            ),
          )
          as _i13.Future<List<_i5.SubscriptionDomain>>);
}

/// A class which mocks [ISelectSubscription].
///
/// See the documentation for Mockito's code generation for more information.
class MockISelectSubscription extends _i1.Mock
    implements _i29.ISelectSubscription {
  MockISelectSubscription() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<void> call({required String? id}) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#id: id}),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);
}

/// A class which mocks [ICancelSubscription].
///
/// See the documentation for Mockito's code generation for more information.
class MockICancelSubscription extends _i1.Mock
    implements _i30.ICancelSubscription {
  MockICancelSubscription() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<void> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);
}

/// A class which mocks [IGetCategories].
///
/// See the documentation for Mockito's code generation for more information.
class MockIGetCategories extends _i1.Mock implements _i31.IGetCategories {
  MockIGetCategories() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<List<_i32.CategoryDomain>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i13.Future<List<_i32.CategoryDomain>>.value(
              <_i32.CategoryDomain>[],
            ),
          )
          as _i13.Future<List<_i32.CategoryDomain>>);
}

/// A class which mocks [IGetNextCard].
///
/// See the documentation for Mockito's code generation for more information.
class MockIGetNextCard extends _i1.Mock implements _i33.IGetNextCard {
  MockIGetNextCard() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i9.KnowledgeCardDomain> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i13.Future<_i9.KnowledgeCardDomain>.value(
              _FakeKnowledgeCardDomain_7(this, Invocation.method(#call, [])),
            ),
          )
          as _i13.Future<_i9.KnowledgeCardDomain>);
}

/// A class which mocks [IGetGuidedRouteIntros].
///
/// See the documentation for Mockito's code generation for more information.
class MockIGetGuidedRouteIntros extends _i1.Mock
    implements _i34.IGetGuidedRouteIntros {
  MockIGetGuidedRouteIntros() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<List<_i35.GuidedRouteIntroDomain>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i13.Future<List<_i35.GuidedRouteIntroDomain>>.value(
              <_i35.GuidedRouteIntroDomain>[],
            ),
          )
          as _i13.Future<List<_i35.GuidedRouteIntroDomain>>);
}

/// A class which mocks [IGetMembership].
///
/// See the documentation for Mockito's code generation for more information.
class MockIGetMembership extends _i1.Mock implements _i36.IGetMembership {
  MockIGetMembership() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i10.MembershipDomain> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i13.Future<_i10.MembershipDomain>.value(
              _FakeMembershipDomain_8(this, Invocation.method(#call, [])),
            ),
          )
          as _i13.Future<_i10.MembershipDomain>);
}

/// A class which mocks [ISaveRecallCard].
///
/// See the documentation for Mockito's code generation for more information.
class MockISaveRecallCard extends _i1.Mock implements _i37.ISaveRecallCard {
  MockISaveRecallCard() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<void> call({required String? cardId}) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#cardId: cardId}),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);
}

/// A class which mocks [ISendAnswer].
///
/// See the documentation for Mockito's code generation for more information.
class MockISendAnswer extends _i1.Mock implements _i38.ISendAnswer {
  MockISendAnswer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<void> call({
    required String? answer,
    required String? revisionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #answer: answer,
              #revisionId: revisionId,
            }),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);
}

/// A class which mocks [IGetCardRevision].
///
/// See the documentation for Mockito's code generation for more information.
class MockIGetCardRevision extends _i1.Mock implements _i39.IGetCardRevision {
  MockIGetCardRevision() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i11.RevisionDomain> call({required String? cardId}) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#cardId: cardId}),
            returnValue: _i13.Future<_i11.RevisionDomain>.value(
              _FakeRevisionDomain_9(
                this,
                Invocation.method(#call, [], {#cardId: cardId}),
              ),
            ),
          )
          as _i13.Future<_i11.RevisionDomain>);
}

/// A class which mocks [User].
///
/// See the documentation for Mockito's code generation for more information.
class MockUser extends _i1.Mock implements _i40.User {
  MockUser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i41.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  Map<String, dynamic> get appMetadata =>
      (super.noSuchMethod(
            Invocation.getter(#appMetadata),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  String get aud =>
      (super.noSuchMethod(
            Invocation.getter(#aud),
            returnValue: _i41.dummyValue<String>(this, Invocation.getter(#aud)),
          )
          as String);

  @override
  String get createdAt =>
      (super.noSuchMethod(
            Invocation.getter(#createdAt),
            returnValue: _i41.dummyValue<String>(
              this,
              Invocation.getter(#createdAt),
            ),
          )
          as String);

  @override
  bool get isAnonymous =>
      (super.noSuchMethod(Invocation.getter(#isAnonymous), returnValue: false)
          as bool);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}
