name: widgetbook_workspace
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  auror:
    path: ../

  flutter_bloc: ^9.1.1

  auror_design_system:
    path: ../packages/auror_design_system

  google_fonts: ^6.2.1
  widgetbook: ^3.22.0
  widgetbook_annotation: ^3.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  widgetbook_generator: ^3.22.0
  build_runner: ^2.13.1

flutter:
  uses-material-design: true
